# Generated by Django 4.2.11 on 2024-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskDate',
            field=models.DateField(),
        ),
    ]
